### ISSUE TITLE
[BUG] Docker status is unhealthy

### ISSUE THREAD

**Issue by UberDudePL** [hywax/mafl#100]
### Environment

Self-Hosted (Docker)

### System

Proxmox LXC

### Version

0.15.0

### Describe the problem

Status in Portainer for mafl is Unhealthy with following error message:
OCI runtime exec failed: exec failed: unable to start container process: exec: "/bin/sh": stat /bin/sh: no such file or directory: unknown

### Additional info

![image](https://github.com/hywax/mafl/assets/91315950/d22cdb63-4c96-4a88-8a83-012a955ace11)

**Comment by hywax** [comment]
Hi, I know that there is this bug. I will try to resolve it as soon as possible. It does not affect the service

**Comment by hywax** [comment]
As it turns out it's not very hard to do. The changes will be in the new version [v0.15.1](https://github.com/hywax/mafl/releases/tag/v0.15.1)
