### ISSUE TITLE
[FEATURE_REQUEST] unRAID XML Template or Support

### ISSUE THREAD

**Issue by Sonny-Crockett** [hywax/mafl#102]
### Is your feature request related to a problem? If so, please describe.

I am going to try and install a package from DockerHub onto unraid but would love to see unRAID support as its a very sharp looking startpage, and I'd love more people to have easy access to it.

### Describe the solution you'd like

XML added here [https://forums.unraid.net/topic/57181-docker-faq/#comment-566084](url)

### Priority

Medium (Would be very useful)

### Is this something you would be keen to implement

None

**Comment by hywax-assistant** [comment]
👋 @Sonny-Crockett
Thanks for opening your first issue here!
To help make it easier for us to investigate your issue, please follow the [contributing guidelines](https://mafl.hywax.space/community/contributing.html).

 If you like this project, please ⭐ star our repo.

**Comment by Sonny-Crockett** [comment]
Awesome no rush! Thanks!! Have a safe trip.

**Comment by Sonny-Crockett** [comment]
[https://github.com/selfhosters/unRAID-CA-templates/issues/491](url)

I have requested for it to be added to CA applist. Thank you for your work. 

Once its added I will download and test it. Anyone who wants to jump ahead with a by adding it via user template can try as well!

**Comment by nwithan8** [comment]
@hywax I will test your XML file right now and we'll get it added to CA under the "selfhosters" repository.
