### ISSUE TITLE
[QUESTION] Is the docs site down?

### ISSUE THREAD

**Issue by viharm** [hywax/mafl#111]
### Question

I have been trying to test this out, but the site ([mafl.hywax.space](https://mafl.hywax.space/)) linked in the README appears down. Is it just me? Or is anyone else also having issues with this?

### Category

Documentation

**Comment by hywax-assistant** [comment]
👋 @viharm
Thanks for opening your first issue here!
To help make it easier for us to investigate your issue, please follow the [contributing guidelines](https://mafl.hywax.space/community/contributing.html).

 If you like this project, please ⭐ star our repo.

**Comment by hywax** [comment]
What exactly are the problems? The site is hosted on GitHub Pages. It should be available at all times.

All documentation source code is in the docs folder.

**Comment by viharm** [comment]
It appears that some of my devices in my network were having DNS issues. I’ve tried again, and it works. Sorry about the false alarm.

This product looks good, thanks for your efforts.

**Comment by viharm** [comment]
Not reproducible
