### ISSUE TITLE
[QUESTION] Does every change in config.yml need to restart whole service?

### ISSUE THREAD

**Issue by nkkfs** [hywax/mafl#112]
### Question

Hello, I'm using Mafl on UnRAID as they added it to their appstore repo.
Overall no bugs so far but I don't know that Am I doing something wrong or every change in config.yml file need to be preceded by a restart of the entire service?

### Category

App Usage

**Comment by hywax-assistant** [comment]
👋 @nkkfs
Thanks for opening your first issue here!
To help make it easier for us to investigate your issue, please follow the [contributing guidelines](https://mafl.hywax.space/community/contributing.html).

 If you like this project, please ⭐ star our repo.

**Comment by hywax** [comment]
Hi, what version of mafl are you using?  In the latest versions it is added to update the config after changing a file

**Comment by nkkfs** [comment]
Hi @hywax, I'm using latest version and still not getting updated after changing file. How can I fix that?
