### ISSUE TITLE
[SHOWCASE] crueber home mafl

### ISSUE THREAD

**Issue by crueber** [hywax/mafl#116]
### Title

Home lab dashboard

### Screenshot

![2024-06-08_12-35](https://github.com/hywax/mafl/assets/703845/aa4d33b2-d577-4942-bc56-2c1c392c3377)

### Would you like your name/ username included?

Yes

### Link to your Website/ Profile/ Twitter (optional)

https://github.com/crueber

**Comment by hywax-assistant** [comment]
👋 @crueber
Thanks for opening your first issue here!
To help make it easier for us to investigate your issue, please follow the [contributing guidelines](https://mafl.hywax.space/community/contributing.html).

**Comment by hywax** [comment]
Thank you for your contribution! Added your example to [showcase](https://mafl.hywax.space/community/showcase.html)!
