### ISSUE TITLE
[QUESTION] Ability to use HTTPS for the MAFL page

### ISSUE THREAD

**Issue by afsy-d** [hywax/mafl#119]
### Question

Hi all,

Is there an option available to allow the MAFL page to run on SSL. I am using a wildcard cert for the domain and would like to use the main certificate to ensure the page is served via HTTPS instead of HTTP.

### Category

Configuration

**Comment by hywax-assistant** [comment]
👋 @afsy-d
Thanks for opening your first issue here!
To help make it easier for us to investigate your issue, please follow the [contributing guidelines](https://mafl.hywax.space/community/contributing.html).

 If you like this project, please ⭐ star our repo.

**Comment by hywax** [comment]
ENV `NITRO_SSL_CERT` and `NITRO_SSL_KEY` - if both are present, this will launch the server in HTTPS mode. In the vast majority of cases, this should not be used other than for testing, and the Nitro server should be run behind a reverse proxy like nginx/traefik or Cloudflare which terminates SSL.
