### ISSUE TITLE
[BUG] Incorrect Type for /app/data/config.yml Path in Container

### ISSUE THREAD

**Issue by Sergo1217** [hywax/mafl#123]
### Environment

Self-Hosted (Docker)

### System

Ubuntu 22.04, Docker 27.0.3

### Version

0.15.3

### Describe the problem

![image](https://github.com/hywax/mafl/assets/16447886/4a86d942-e74a-4b91-adc8-374e7f539e3b)

**Comment by hywax-assistant** [comment]
👋 @Sergo1217
Thanks for opening your first issue here!
To help make it easier for us to investigate your issue, please follow the [contributing guidelines](https://mafl.hywax.space/community/contributing.html).

 If you like this project, please ⭐ star our repo.
