### ISSUE TITLE
Update Documentation about Proxmox

### ISSUE THREAD

**Issue by MickLesk** [hywax/mafl#148]
### Environment

Other (Specify below)

### Describe the problem

Hi :-)

I am the maintainer of community-scripts\ProxmoxVE. I was already involved in the tteck project back then.

Unfortunately, tteck passed away last week and I have now founded an ORG with a small team. tteck was still with us and supported us.

Your link in your readme of the project is still the wrong one, it is accessible because we have agreed on a public archive, but it is not updated and maintained.

The project can now be found here.
https://github.com/community-scripts/ProxmoxVE

The website is here:
https://community-scripts.github.io/ProxmoxVE/ or https://helper-scripts.com 

### Additional info

https://github.com/community-scripts/ProxmoxVE/discussions/237

**Comment by hywax-assistant** [comment]
👋 @MickLesk
Thanks for opening your first issue here!
To help make it easier for us to investigate your issue, please follow the [contributing guidelines](https://mafl.hywax.space/community/contributing.html).

 If you like this project, please ⭐ star our repo.

**Comment by hywax** [comment]
Hi, okay, I'll fix that soon
