### ISSUE TITLE
[BUG] <title>Error 500 Oops! There's been an unexpected error

### ISSUE THREAD

**Issue by coracoo** [hywax/mafl#18]
### Environment

Self-Hosted (Docker)

### System

Linux 5.15.0-78-generic #85-Ubuntu SMP Fri Jul 7 15:25:09 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Version

hywax/mafl

### Describe the problem

Hello, it is looks a beautiful homepage, and I like it, but seem something happen when I used the docker cli with hywax/mafl.

-------------------------------------
```
Listening on http://[::]:3000
ZodError: [
  {
    "code": "invalid_union",
    "unionErrors": [
      {
        "issues": [
          {
            "code": "invalid_type",
            "expected": "array",
            "received": "undefined",
            "path": [
              "services"
            ],
            "message": "Required"
          }
        ],
        "name": "ZodError"
      },
      {
        "issues": [
          {
            "code": "invalid_type",
            "expected": "object",
            "received": "undefined",
            "path": [
              "services"
            ],
            "message": "Required"
          }
        ],
        "name": "ZodError"
      }
    ],
    "path": [
      "services"
    ],
    "message": "Invalid input"
  }
]
    at get error [as error] (file:///app/server/node_modules/zod/lib/index.mjs:538:31)
    at ZodObject.parse (file:///app/server/node_modules/zod/lib/index.mjs:638:22)
    at validateConfigSchema (file:///app/server/chunks/nitro/node-server.mjs:5176:17)
    at loadLocalConfig (file:///app/server/chunks/nitro/node-server.mjs:5189:5)
    at async file:///app/server/chunks/nitro/node-server.mjs:5229:23 {
  issues: [
    {
      code: 'invalid_union',
      unionErrors: [Array],
      path: [Array],
      message: 'Invalid input'
    }
  ],
  addIssue: [Function (anonymous)],
  addIssues: [Function (anonymous)],
  errors: [
    {
      code: 'invalid_union',
      unionErrors: [Array],
      path: [Array],
      message: 'Invalid input'
    }
  ]
}
[Vue warn]: Component <Anonymous> is missing template or render function.
```

**Comment by hywax** [comment]
Hi, I'm surprised someone's already using it. I haven't even had time to translate the documentation into English yet.

By mistake the config is not filled in correctly. Can you show me your config?

**Comment by coracoo** [comment]
oh! I know why the mistake happen. I did't download the config.yml, just use the docker-compose then config.yml in my linux became a folder.
Then I try to use the following cli
`docker run -d --name mafl -p 12345:3000 -v /home/mafl:/app/data hywax/mafl`
but there is nothing in /home/mafl 
haha ~~
```
version: '3.8'

services:
  mafl:
    image: hywax/mafl
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - ./config.yml:/app/data/config.yml
```

**Comment by hywax** [comment]
You can get a sample config here - https://github.com/hywax/mafl/tree/main/.example

I will try to translate the documentation into English in the near future. At the moment it is available in Russian - https://mafl.hywax.space/ru/reference/configuration.html.

If you need help, open an issue I'm always happy to help.
