### ISSUE TITLE
[FEATURE_REQUEST] Add target=”_blank” attribute as config option alongside theme&title

### ISSUE THREAD

**Issue by jacob2020baklas** [hywax/mafl#23]
### Is your feature request related to a problem? If so, please describe.

Add target=”_blank” attribute as config option alongside theme&title

### Describe the solution you'd like

Add target=”_blank” attribute as config option alongside theme&title

### Priority

High (The app does not function without it)

### Is this something you would be keen to implement

None

**Comment by hywax** [comment]
Hi, thanks for the idea!

It's pretty quick and easy to do. So I'll add it in the next update. Which will be released today!

**Comment by hywax** [comment]
Feature has been added in the new version [0.7.6](https://github.com/hywax/mafl/releases/tag/v0.7.6).

The ability to specify [target](https://mafl.hywax.space/reference/configuration.html#behaviour) globally in `config.yml` has been added. And you can also add [target](https://mafl.hywax.space/services/base.html#target) to individual services separately.

Thanks for the great idea! I'll be happed your star on github!
