### ISSUE TITLE
[FEATURE_REQUEST] Center elements vertical and horizontal

### ISSUE THREAD

**Issue by hellomarb** [hywax/mafl#49]
### Describe the solution you'd like

It would be great to have a configuration option to center the output vertical and horizontal and set the max-width from a fixed value to auto. For large screens this would be a great addition.

### Priority

Low (Nice-to-have)

### Is this something you would be keen to implement

No

**Comment by hywax-assistant** [comment]
👋 @hellomarb
Thanks for opening your first issue here!
To help make it easier for us to investigate your issue, please follow the [contributing guidelines](https://mafl.hywax.space/community/contributing.html).

 If you like this project, please ⭐ star our repo.
