### ISSUE TITLE
[BUG] Theme does not work

### ISSUE THREAD

**Issue by UberDudePL** [hywax/mafl#56]
### Environment

Self-Hosted (Docker)

### System

Chrome 122.0.6261.95, Docker in Proxmox, Safari on iPhone

### Version

0.9.2

### Describe the problem

Hello, 
First of all, Thank you for creating this beaty. I was building my won homepage with such look myself but using old html :)
I've create my config. All is working great apart from themes. No matter which theme I select it always uses System. On Chrome I have light but on my iPhone dark it running as it is night. Most probably in the morning it will change to light. On Opera I default to dark as well due to browser settings

### Additional info

title: UberDude's Homepage
lang: en
theme: deep
checkUpdates: true
behaviour:
  target: _blank
services:
  Home:
    - title: Home Assistant
      description: Home automation
      link: https://xyz/
      icon:
        name: simple-icons:homeassistant
      status:
        enabled: true
  Media:
    - title: Plex
      description: Plex Media Server
      link: http://xyz/
      icon:
        name: mdi:plex
    - title: qBittorrent
      description: qBittorren Panel
      link: http://xyz/  
      icon:
        name: simple-icons:qbittorrent
  Admin:
    - title: Pi Hole
      description: qBittorren Panel
      link: http://xyz/
      icon:
        name: mdi:pi-hole

**Comment by hywax-assistant** [comment]
👋 @UberDudePL
Thanks for opening your first issue here!
To help make it easier for us to investigate your issue, please follow the [contributing guidelines](https://mafl.hywax.space/community/contributing.html).

 If you like this project, please ⭐ star our repo.

**Comment by hywax** [comment]
@UberDudePL hey, yeah, there was a problem. Fixed it in [v0.9.4](https://github.com/hywax/mafl/releases/tag/v0.9.4). 

Thank you so much for your contribution!
