### ISSUE TITLE
[QUESTION] How to update

### ISSUE THREAD

**Issue by tinju87** [hywax/mafl#61]
### Question

Hi, 

How can I update mafl? 
When I enter "update" in the mafl LXC I got this:

```
    __  ___      ______
   /  |/  /___ _/ __/ /
  / /|_/ / __ `/ /_/ /
 / /  / / /_/ / __/ /
/_/  /_/\__,_/_/ /_/

 ✗ There is currently no update path available.
root@mafl:/# 
```

Thanks for help.

### Category

Setup and Deployment

**Comment by hywax-assistant** [comment]
👋 @tinju87
Thanks for opening your first issue here!
To help make it easier for us to investigate your issue, please follow the [contributing guidelines](https://mafl.hywax.space/community/contributing.html).

 If you like this project, please ⭐ star our repo.

**Comment by hywax** [comment]
Hi, there is indeed such a problem. I will try to solve it soon

**Comment by hywax** [comment]
I have created a PR to the project where the .sh script is stored.

Temporary solution, run the LXC terminal:
```
bash -c "$(wget -qLO - https://github.com/hywax/Proxmox/raw/main/ct/mafl.sh)"
```
