### ISSUE TITLE
[FEATURE_REQUEST] Reloading config.yml

### ISSUE THREAD

**Issue by abby606** [hywax/mafl#66]
### Question

I love the look and simplicity of mafl, thank you for your work!

Stupid question perhaps but changing the config.yml does not have instant results and in order to see my changes, I need to restart the mafl service - is this expected or am I doing something wrong?

thank you

### Category

App Usage

**Comment by hywax-assistant** [comment]
👋 @abby606
Thanks for opening your first issue here!
To help make it easier for us to investigate your issue, please follow the [contributing guidelines](https://mafl.hywax.space/community/contributing.html).

 If you like this project, please ⭐ star our repo.

**Comment by hywax** [comment]
Hi! Thanks!

This is the correct behavior at the moment. Now I'm working on not having to restart the service.

I will leave the issue open until this functionality is available.

**Comment by abby606** [comment]
Thank you very much!

**Comment by snickerweb** [comment]
Hi. How I can restart the service?

**Comment by andrewbeaton** [comment]
As a work around, I've setup a oneshot and path unit service to monitor changes to the mafl config and restart the main mafl service.

Here's a quick shell script to set it up.

mafl-restart-service.sh
```
#!/usr/bin/env bash

echo -e "Creating oneshot service"
cat <<EOF >/etc/systemd/system/mafl-restart.service
[Service]
Type=oneshot
ExecStart=/usr/bin/systemctl restart mafl
EOF
echo -e "Created oneshot service"

echo -e "Creating path unit"
cat <<EOF >/etc/systemd/system/mafl-restart.path
[Path]
PathChanged=/opt/mafl/data/config.yml

[Install]
WantedBy=multi-user.target
EOF
echo -e "Created path unit"

systemctl enable --now mafl-restart.path 
```

**Comment by snickerweb** [comment]
Can you explain in step by step? ;)

nano mafl-restart.path 

copy/paste this: #1...........unit"

systemctl enable --now mafl-restart.path 

and now?

**Comment by hywax** [comment]
I didn't realize this was such a hot topic. I'll try to do a hot reboot as soon as possible when changing config

**Comment by snickerweb** [comment]
andrewbeatons script work fine.
I think a good thing is a reload button on the webpage bottom right. Can be switched off if the webpage is publicly accessible.

**Comment by hywax** [comment]
@abby606 @snickerweb @andrewbeaton 

The next update will add a feature to automatically update when the config is changed. The functionality has already been made, now it is being tested.

Thank you for your contribution!

**Comment by jill88** [comment]
Did this ever get implemented?  It doesn't appear so to me, unless I am missing something.  Thanks.
