### ISSUE TITLE
[FEATURE_REQUEST] PWA color head

### ISSUE THREAD

**Issue by hywax** [hywax/mafl#69]
### Describe the solution you'd like

Right now, when creating a PWA, the header has a white fill color. It should be changed to bend color

### Priority

Low (Nice-to-have)

### Is this something you would be keen to implement

None

**Comment by hywax-assistant** [comment]
👋 @hywax
Thanks for opening your first issue here!
To help make it easier for us to investigate your issue, please follow the [contributing guidelines](https://mafl.hywax.space/community/contributing.html).

 If you like this project, please ⭐ star our repo.
