### ISSUE TITLE
[SHOWCASE] Simple Dashboard

### ISSUE THREAD

**Issue by splnut** [hywax/mafl#71]
### Title

My Simple Dashboard

### Screenshot

https://imgur.com/a/5ITW0Ql
![Screenshot 2024-03-28 225816](https://github.com/hywax/mafl/assets/930825/71598445-ec44-4f9a-b1fa-fc360f6defac)

### Would you like your name/ username included?

No

**Comment by hywax-assistant** [comment]
👋 @splnut
Thanks for opening your first issue here!
To help make it easier for us to investigate your issue, please follow the [contributing guidelines](https://mafl.hywax.space/community/contributing.html).

 If you like this project, please ⭐ star our repo.

**Comment by hywax** [comment]
Thank you for your contribution! Added your example to [shwcase](https://mafl.hywax.space/community/showcase.html)!
