### ISSUE TITLE
[FEATURE_REQUEST] Status LED over Ping or Network Lookup

### ISSUE THREAD

**Issue by snickerweb** [hywax/mafl#85]
Status LED can only be used if the target has a WebUI.
(proxmox also does not work although WebUI )
Here an example:
![Screenshot 2024-04-10 010015](https://github.com/hywax/mafl/assets/7456455/2f7f96e9-5e0d-4364-8ab6-23928bca3bd9)

It would be good if the status LED also simply looked for IP addresses via a ping or something like the tool "Advanced IP Scanner"

**Comment by hywax-assistant** [comment]
👋 @snickerweb
Thanks for opening your first issue here!
To help make it easier for us to investigate your issue, please follow the [contributing guidelines](https://mafl.hywax.space/community/contributing.html).

 If you like this project, please ⭐ star our repo.

**Comment by snickerweb** [comment]
Hi Hywax,
do you know why the status LED does not work on the Proxmox web frontend?

Thanks for your work. I love how simple your programm is.

**Comment by hywax** [comment]
@snickerweb most likely due to http error, which can be in case of missing proxmox ssl certificate. Since the availability check uses GET request.

I will think how to rewrite this functionality.

PS I have access to proxmox via reverse proxy and the indicator works correctly.

**Comment by hywax** [comment]
As it turns out it's not very hard to do. The changes will be in the new version v0.13.0
