### ISSUE TITLE
0.12 update update fail over tteck

### ISSUE THREAD

**Issue by snickerweb** [hywax/mafl#89]
Update over tteck do this at the end:

`<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
----- Native stack trace -----

 1: 0xb84bd6 node::OOMErrorHandler(char const*, v8::OOMDetails const&) [/usr/bin/node]
 2: 0xefec30 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, v8::OOMDetails const&) [/usr/bin/node]
 3: 0xefef17 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, v8::OOMDetails const&) [/usr/bin/node]
 4: 0x1110925  [/usr/bin/node]
 5: 0x1110eb4 v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) [/usr/bin/node]
 6: 0x1127da4 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::internal::GarbageCollectionReason, char const*) [/usr/bin/node]
 7: 0x11285bc v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/bin/node]
 8: 0x10fe8c1 v8::internal::HeapAllocator::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/bin/node]
 9: 0x10ffa55 v8::internal::HeapAllocator::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/bin/node]
10: 0x10dd0a6 v8::internal::Factory::NewFillerObject(int, v8::internal::AllocationAlignment, v8::internal::AllocationType, v8::internal::AllocationOrigin) [/usr/bin/node]
11: 0x1537e36 v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [/usr/bin/node]
12: 0x1971ef6  [/usr/bin/node]
|Aborted
error Command failed with exit code 134.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

[ERROR] in line 68: exit code 0: while executing command yarn build

root@mafl:~# nano /opt/mafl/data/config.yml`

**Comment by hywax** [comment]
Hi, you don't have enough memory in the lxc container. This is because the application is build from source. 

The solution would be to increase the RAM memory of the container.

**Comment by snickerweb** [comment]
Now I make a new tteck lxc. Works fine.

Maybe tteck should give as standard more ram

**Comment by hywax** [comment]
How much memory did you have at the time of the error?

**Comment by snickerweb** [comment]
2gb

**Comment by hywax** [comment]
That's a lot, 1gb should be enough. 

The script is in another repository (tteck). Maybe something in it has changed, it used to require less to update. 

I'll try to fix it or ask tteck for help.

**Comment by hywax** [comment]
Added documentation on this error - https://mafl.hywax.space/guide/getting-started.html#proxmox
