### ISSUE TITLE
[QUESTION] Use own icons -  Proxmox LXC

### ISSUE THREAD

**Issue by Cube29** [hywax/mafl#96]
### Question

Where I have to store my own icons "physically" in the Proxmox LXC Container?
There is no information in the documentation.

### Category

Using Icons

**Comment by hywax-assistant** [comment]
👋 @Cube29
Thanks for opening your first issue here!
To help make it easier for us to investigate your issue, please follow the [contributing guidelines](https://mafl.hywax.space/community/contributing.html).

 If you like this project, please ⭐ star our repo.

**Comment by hywax** [comment]
Hi, added paths to the documentation


| Path                             | Type   | Description                                            |
|----------------------------------|--------|--------------------------------------------------------|
| `/opt/mafl/data/data/config.yml` | File   | App configuration - [more](https://mafl.hywax.space/reference/configuration.html) |
| `/opt/mafl/data/public/icons`    | Folder | Local icons - [more](https://mafl.hywax.space/reference/icons.html)               |
| `/opt/mafl/data/public/favicons` | Folder | Favicon icons - [more](https://mafl.hywax.space/reference/favicons.html)          |

Thank you for your contribution!
